### ISSUE TITLE
Error for pypgx installed by conda

### ISSUE THREAD

**Issue by geocarvalho** [sbslee/pypgx#60] opened 2022-05-27 13:36 UTC
Hello team, thank you for making this nice project available.
I have installed `pypgx` using `conda`, but when I try to check the tool I have the error below:
```
$ pypgx -h
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/pypgx", line 6, in <module>
    from pypgx.__main__ import main
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pypgx/__main__.py", line 4, in <module>
    from .cli import commands
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pypgx/cli/__init__.py", line 9, in <module>
    commands[f.stem.replace('_', '-')] = import_module(f'.{f.stem}', __package__)
  File "/home/ubuntu/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pypgx/cli/compute_control_statistics.py", line 18, in <module>
    $ pypgx {fuc.api.common._script_name()} \\
AttributeError: module 'fuc.api.common' has no attribute '_script_name'
```

Not sure how to solve it, could you help?

**Comment by sbslee** [comment] 2022-05-27 13:58
@geocarvalho,

Thanks for your interest in PyPGx! The problem is most likely caused because you are using an old version of the `fuc` package, which is one of the required packages for running PyPGx. You can see which version of `fuc` you are using by :

```
$ conda list | grep "fuc"
```

FYI, the most current version is `0.33.1`. In fact, if you are installing PyPGx for the first time, here's what I recommend:

```
$ conda create -n pypgx -c bioconda pypgx=0.15.0 fuc=0.33.1
```

Also, please don't forget to install the resource bundle:

```
$ cd ~
$ git clone --branch 0.15.0 --depth 1 https://github.com/sbslee/pypgx-bundle
``` 

Let me know if the problem doesn't get resolved by above.

**Comment by sbslee** [comment] 2022-05-30 10:20
Please feel free to re-open this if you have additional questions!

**Closed as completed by sbslee** 2022-05-30 10:20 UTC
