### ISSUE TITLE
CYP2B6 phenotyping/genotyping

### ISSUE THREAD

**Issue by Pharmacogenetecist** [sbslee/pypgx#46] opened 2022-01-24 02:03 UTC
Hello folks,
I think there maybe an issue with the way *6 and *9 are being assigned. At the end of the day they are both decreased function alleles, so it should not impact on phenotype, but it will mess with any allele frequency comparisons.

As per https://www.pharmvar.org/gene/CYP2B6

*4 = 18053A>G 
*6 = 15631G>T  AND  18053A>G
*9 = 15631G>T

When putting our GSA imputed data through PYPGX, we got our previously assigned (by sanger) *6 being assigned as *9.  Possibly something to follow up on.

**Comment by sbslee** [comment] 2022-01-24 02:54
@Pharmacogenetecist,

I think I'm having some trouble understanding the nature of the issue. Are you implying that when a given haplotype has both 15631G>T and 18053A>G, you would rather assign it as *9 instead of *6?

**Comment by Pharmacogenetecist** [comment] 2022-01-24 03:02
Rather when a given haplotype has both 15631G>T and 18053A>G it should be assigned *6, however, we are getting *9 after using imputed GSA array data.

**Comment by sbslee** [comment] 2022-01-24 03:11
Got it. There are a number of possible explanations for this:

1. Did you make sure the sample in the imputed VCF has both 15631G>T and 18053A>G? In other words, is it possible that 18053A>G was not imputed at all (e.g. not present in the reference haplotype panel)?
2. If you are certain that both 15631G>T and 18053A>G are present in the sample's VCF, another explanation is that both variants were phased in trans as opposed to in cis (*1/*6 vs. *4/*9). But in this case, the `AlternativePhase` column in the `SampleTable[Results]` file should indicate *6 as a possible candidate star allele for that sample. Please check that file.
3. If you can send me the input VCF file and the exact command you used, I can try to reproduce the issue.
4. What version of PyPGx are you using?

**Comment by Pharmacogenetecist** [comment] 2022-01-24 05:41
> Got it. There are a number of possible explanations for this:
> 
> 1. Did you make sure the sample in the imputed VCF has both 15631G>T and 18053A>G? In other words, is it possible that 18053A>G was not imputed at all (e.g. not present in the reference haplotype panel)?
> 2. If you are certain that both 15631G>T and 18053A>G are present in the sample's VCF, another explanation is that both variants were phased in trans as opposed to in cis (*1/*6 vs. *4/*9). But in this case, the `AlternativePhase` column in the `SampleTable[Results]` file should indicate *6 as a possible candidate star allele for that sample. Please check that file.
> 3. If you can send me the input VCF file and the exact command you used, I can try to reproduce the issue.
> 4. What version of PyPGx are you using?

Thanks I will double check and get back to you.

**Comment by Pharmacogenetecist** [comment] 2022-01-24 21:27
Regarding point 1 - you are right.
18053A>G (rs2279343) has not been genotyped or imputed, therefore the report of everything being *9.

Apologies for this.

**Comment by sbslee** [comment] 2022-01-24 23:33
No worries. Few points to keep in mind:

1. rs2279343 is a relatively common variant with allele frequency of 0.1472 according to [gnomAD](https://gnomad.broadinstitute.org/variant/19-41515263-A-G?dataset=gnomad_r2_1). Therefore, the fact that your imputed VCF did not have any information about this variant makes me wonder whether the imputation process worked as you expected. So I would first make sure the VCF you used as input for PyPGx is actually an imputed VCF, as opposed to the original VCF without imputation.
2. If you believe there was an issue during imputation, you may want to consider doing imputation within PyPGx. Since your input data is GSA from Illumina, you can use the `run-chip-pipeline` command to perform imputation during genotype analysis:
```
$ pypgx run-chip-pipeline \
CYP2B6 \
CYP2B6-pipeline \
variants-without-imputation.vcf.gz \
--impute
```
Above will use the 1000 Genomes Project reference haploid panel for haplotype phasing + imputation.

**Comment by Pharmacogenetecist** [comment] 2022-01-24 23:51
Thank you.
The VCF file used was definitely imputed, I double checked. We used the (https://imputationserver.sph.umich.edu/) to do this. I will see if I can use the original non-imputed file to redo it using your pipeline.
Thanks.

**Comment by sbslee** [comment] 2022-02-01 11:37
Closing this for now -- please feel free to reopen it if necessary.

**Closed as completed by sbslee** 2022-02-01 11:37 UTC
